ex1

In [ ]:
import numpy as np
arr = np.arange(15)

print(arr)

[0 1 2 3 4 5 6 7 8 9]



ex2


In [3]:
lst = [3.14, 2.17, 0, 1, 2]
arr = np.array(lst, dtype=int)
print(arr)

[3 2 0 1 2]


ex3

In [4]:
arr = np.arange(1, 10).reshape(3, 3)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


ex4

In [5]:
arr = np.random.rand(4, 5)

print(arr)

[[0.4929744  0.26160143 0.93667835 0.45563834 0.61811803]
 [0.6005646  0.93124689 0.60966734 0.61499265 0.31394162]
 [0.12961454 0.37069866 0.55887818 0.69769386 0.69869672]
 [0.6348395  0.99947209 0.36276029 0.50877192 0.95322485]]


ex5

In [6]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
second_row = arr[1]

print(second_row)


[40 50 60]


ex6

In [8]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)

[5 4 3 2 1]


ex7

In [9]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


ex8

In [10]:
arr = np.array([10, 20, 30, 40, 50])


total = np.sum(arr)


average = np.mean(arr)

print("Sum:", total)
print("Average:", average)

Sum: 150
Average: 30.0


ex9

In [14]:
arr = np.arange(1, 21)
print(arr)
print("==================")
reshaped_arr = arr.reshape(4, 5)
print(reshaped_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_numbers = arr[arr % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]
